imports:
    - { resource: "fixtures.yaml" }
    - { resource: "resources.yaml" }
    - { resource: "services.yaml" }
    - { resource: "events.yaml" }
    - { resource: "form_types.yaml" }
    - { resource: "grids.yaml" }
    - { resource: "richeditor.yaml" }

framework:
    validation:
        mapping:
            paths:
                - "%kernel.project_dir%/src/Resources/config/validation/"
